organization:
  name: "${ORGANISATION_NAME}"

clusters:
  - id: default
    name: Clp Cluster
    color: "#ec0000"
    ignoreUntrustedCertificate: false
    bootstrapServers: "$KAFKA_BOOTSTRAP_SERVER"
    properties:
    schemaRegistry:
      url: "$SR_SERVER"
      ignoreUntrustedCertificate: false
      properties:
    labels: {}

auth:
  demo-users:
    - email: "${CDK_ADMIN_EMAIL}"
      password: "${CDK_ADMIN_PASSWORD}"
      groups:
        - ADMIN
