package com.example.eventcommons.event.product.event;

public enum ProductEventType {
    PRODUCT_CREATED,
    PRODUCT_UPDATED,
    PRODUCT_MODIFIED,
    PRODUCT_RENEWED,
    PRODUCT_RESIGNED,
    PRODUCT_CANCELED,
    PRODUCT_REJECTED,
    PRODUCT_PERSISTED,
    PRODUCT_REMOVED,
    PRODUCT_RELATIONS_CHANGED,
    PRODUCT_RELATIONS_PERSISTED,
    PRODUCT_STANDARD_CHANGED,
    PRODUCT_STANDARD_PERSISTED
}
